### ISSUE TITLE
Plugin has outdated/broken GitHub links

### ISSUE THREAD

**Issue by iggbodiam** [getgrav/grav-plugin-auto-date#2]
**Steps:**
- Go to the plugin info page
- Click any Github linking page, for this I used the Readme.md link

**is:**
- Reaches a 404 not found page
- Affects all github links for that plugin
- Directs to a wrong/old github directory
https://github.com/team-grav/*

**should:**
- Need to direct to the new github directory
https://github.com/getgrav/*

**Comment by flaviocopes** [comment]
Thanks for reporting
