### ISSUE TITLE
Auto publish date on page publish?

### ISSUE THREAD

**Issue by dotvhs** [getgrav/grav-plugin-auto-date#3]
Great thanks for this plugin, it's very helpful! If I may ask - would it be possible to add an optional setting so it would also (or instead) auto add the "published date" on page publish?

Thanks in advance for your answer and hard work.

**Comment by rhukster** [comment]
https://learn.getgrav.org/content/headers#publish-date

This already exists.  You can access this date via Twig template by using:

```
{{ page.publishDate() }}
```

**Comment by dotvhs** [comment]
I managed to write it myself. It was easier than I thought it will be.

Thanks for your time anyway!
